# Generated by Django 5.2.7 on 2025-10-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'customer'), ('delivery_boy', 'Delivery Boy')], default='customer', max_length=20),
        ),
    ]
