# Generated by Django 5.1.1 on 2025-11-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_reset_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
