# Generated by Django 5.2.7 on 2025-10-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default=1, upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
