# Generated by Django 5.2.7 on 2025-10-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_user_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pic',
            new_name='user_profile',
        ),
    ]
