# Generated by Django 5.1.1 on 2025-11-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor', 'vendor'), ('customer', 'customer'), ('delivery_boy', 'delivery_boy')], default='customer', max_length=20),
        ),
    ]
