# Generated by Django 5.2.7 on 2025-10-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_rename_pic_user_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor', 'vendor'), ('customer', 'customer'), ('delivery_boy', 'delivery_boy')], default='customer', max_length=20),
        ),
    ]
