# Generated by Django 5.2.7 on 2025-10-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_name_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
