# Generated by Django 5.2.7 on 2025-10-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_checkout_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CARD', 'Cash Card'), ('STRIPE', 'Stripe')], default='COD', max_length=10),
        ),
    ]
