# Generated by Django 5.2.7 on 2025-10-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_checkout_is_processed_alter_checkout_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
