# Generated by Django 5.2.7 on 2025-10-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_checkout_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
