# Generated by Django 5.2.7 on 2025-10-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
