# Generated by Django 5.2.7 on 2025-10-23 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_cart_product_cart_quantity_and_more'),
        ('product', '0009_alter_product_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_cart', to='product.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'variant')},
        ),
    ]
