# Generated by Django 5.2.7 on 2025-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_options_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
