# Generated by Django 5.2.7 on 2025-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcard',
            name='card_number',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
